language: csharp
mono: none
dotnet: 1.0.3
dist: trusty
script:
- dotnet restore
deploy:
  provider: releases
  api_key:
    secure: IssHjjHcuzI9l8U02zPNknabzvsPlghca8BX5V+niXRGBM+aZmWKRSDuT+ctuJEud5WDCGImb27fVEU51JaLK4vXr43qARtZyYfzMe5Y1ywCO14el/FZgmP5n0f3v9+vvAy7okC/jCm26m7ApX0HuQt6/6tr4EDxJVGkQokNt53TWDnaimhsHuIpustW0lNJH0xQvK0DqLVxiG3uQOW1WgLzD7HTZEjegnJeBP2XNtJb4N6c447oOv5vUULOM91QRqYqaRYDBD3wnNxH3b2eb/KJonAQ8Ktre8cd3nA9sr4Vf99SvSZXtkxywTz2ngYKl9sM+quX6LgyQDmy/DTA3mkgbj1J8LvSJ2eWe/LSTtHxzQG9PFrfVNiXy6Swn7DIrWVG97cPr/PLwwinacVTI9m4M2ECiO/so1wpmMICgAuB66/1aN6mdgP1OdSzbcuyrGEaN8ZfaW07xVvikmBACDT/4pq5XhyBbNycMkkKzDY0M7YNlSrpQLqb+dGnNtMyj2CJgc3olrGLcY/+br8VUB7BUzFrzMRqLiQEd3dmj5n19zAiEA4d2ieoEh7kkMqMGUQJ2Sb03dzn1Cl7r9j5IN88dr0n25dr01vFBe7+G+hVAhXTPG2JGcIcCRTmv8bkiaoflSxHyGOKfGeD91WUTkQAWDe1OMUi/IyIv7oncuE=
  file_glob: true
  file: "~/build/CapeCrucible/*"
  on:
    repo: CapeCrucible/hackathon-2017-bbbs-backend
  skip_cleanup: true
  on:
    tags: false